# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spec_messages.proto

require 'google/protobuf'


descriptor_data = "\n\x13spec_messages.proto\"\x18\n\tMyMessage\x12\x0b\n\x03msg\x18\x01 \x01(\t\"P\n\x0b\x44\x61teMessage\x12\x17\n\x04type\x18\x01 \x01(\x0e\x32\t.DateType\x12\r\n\x05month\x18\x02 \x01(\x05\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\x05\x12\x0c\n\x04year\x18\x04 \x01(\x05\"\xaa\x01\n\x0e\x43omplexMessage\x12\x17\n\x03msg\x18\x01 \x01(\x0b\x32\n.MyMessage\x12\x0f\n\x07\x63omplex\x18\x02 \x01(\x08\x12\x1a\n\x04\x64\x61te\x18\x03 \x01(\x0b\x32\x0c.DateMessage\x12\r\n\x03uid\x18\x04 \x01(\x05H\x00\x12\x0e\n\x04uuid\x18\x05 \x01(\tH\x00\x12\x0f\n\x07numbers\x18\x06 \x03(\x05\x12\x1c\n\x08messages\x18\x07 \x03(\x0b\x32\n.MyMessageB\x04\n\x02id*+\n\x08\x44\x61teType\x12\x10\n\x0c\x44\x41TE_DEFAULT\x10\x00\x12\r\n\tDATE_BDAY\x10\x01"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

MyMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MyMessage").msgclass
DateMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DateMessage").msgclass
ComplexMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ComplexMessage").msgclass
DateType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DateType").enummodule
